import { supabaseAdmin } from '../config/database';
import logger from '../utils/logger';

export const supportService = {
  // Create support ticket
  async createTicket(userId: string | null, name: string, email: string, message: string): Promise<any> {
    try {
      logger.info(`📧 Creating support ticket for ${email}`);

      // Insert ticket
      const { data: ticket, error } = await supabaseAdmin
        .from('support_tickets')
        .insert({
          user_id: userId,
          name,
          email,
          message
          // created_at auto-generated by database
        })
        .select()
        .single();

      if (error) {
        logger.error('❌ Error creating support ticket:', error);
        throw new Error('Failed to create support ticket');
      }

      logger.info(`✅ Support ticket created: ${ticket.id}`);

      return {
        id: ticket.id,
        name: ticket.name,
        email: ticket.email,
        message: ticket.message,
        createdAt: ticket.created_at
      };
    } catch (error) {
      logger.error('Exception creating support ticket:', error);
      throw error;
    }
  },

  // Get user's tickets
  async getUserTickets(userId: string): Promise<any[]> {
    try {
      const { data: tickets, error } = await supabaseAdmin
        .from('support_tickets')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      if (error) {
        logger.error('Error fetching support tickets:', error);
        return [];
      }

      return tickets || [];
    } catch (error) {
      logger.error('Exception fetching support tickets:', error);
      return [];
    }
  }
};
